/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'process-tracker.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.android-arm64.node')
          } else {
            nativeBinding = require('process-tracker-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'process-tracker.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.android-arm-eabi.node')
          } else {
            nativeBinding = require('process-tracker-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'process-tracker.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.win32-x64-msvc.node')
          } else {
            nativeBinding = require('process-tracker-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'process-tracker.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('process-tracker-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'process-tracker.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('process-tracker-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'process-tracker.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./process-tracker.darwin-universal.node')
      } else {
        nativeBinding = require('process-tracker-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'process-tracker.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.darwin-x64.node')
          } else {
            nativeBinding = require('process-tracker-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'process-tracker.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.darwin-arm64.node')
          } else {
            nativeBinding = require('process-tracker-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'process-tracker.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./process-tracker.freebsd-x64.node')
      } else {
        nativeBinding = require('process-tracker-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-x64-musl.node')
            } else {
              nativeBinding = require('process-tracker-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-x64-gnu.node')
            } else {
              nativeBinding = require('process-tracker-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-arm64-musl.node')
            } else {
              nativeBinding = require('process-tracker-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('process-tracker-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('process-tracker-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('process-tracker-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('process-tracker-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('process-tracker-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'process-tracker.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('process-tracker-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { detectJavaInstallations, validateJavaPath, getRecommendedJavaVersion, findJavaForMinecraft, installJavaRuntime, downloadFile, downloadFiles, verifyFileHash, calculateSha1, calculateSha256, verifyMultipleFileHashes, planServerSyncDownloads, cleanupExtraMods, checkFastModListSync, saveFastModListSyncSnapshot, postInstallModpackFiles, detectModConflictsNative, inspectPackMetadata, scanPackDirectory, exportModpackArchive, LoaderType, getInstancePath, createInstanceDirectories, saveInstanceMeta, loadInstanceMeta, listInstances, deleteInstance, copyInstance, getDirectorySize, listInstanceMods, toggleMod, deleteMod, listInstanceResourcepacks, readLogTail, extractZip, extractZipAsync, extractFilesFromZip, listZipContents, readFileFromZip, parseModrinthManifest, parseCurseforgeManifest, extractModpackOverrides, modrinthSearch, modrinthGetProject, modrinthGetVersions, curseforgeSearch, curseforgeGetFiles, curseforgeGetDownloadUrl, fetchVersionManifest, fetchVersionDetail, prepareLaunch, launchGame, getAssetDownloads, analyzeCrashLog, ForgeLoaderType, runForgeInstaller, installForge, installFabric, getFabricVersions, installQuilt, getQuiltVersions, isProcessAlive, killProcessTree, saveRunningInstance, removeRunningInstance, getRunningInstances, isInstanceRunning, getInstancePid } = nativeBinding

module.exports.detectJavaInstallations = detectJavaInstallations
module.exports.validateJavaPath = validateJavaPath
module.exports.getRecommendedJavaVersion = getRecommendedJavaVersion
module.exports.findJavaForMinecraft = findJavaForMinecraft
module.exports.installJavaRuntime = installJavaRuntime
module.exports.downloadFile = downloadFile
module.exports.downloadFiles = downloadFiles
module.exports.verifyFileHash = verifyFileHash
module.exports.calculateSha1 = calculateSha1
module.exports.calculateSha256 = calculateSha256
module.exports.verifyMultipleFileHashes = verifyMultipleFileHashes
module.exports.planServerSyncDownloads = planServerSyncDownloads
module.exports.cleanupExtraMods = cleanupExtraMods
module.exports.checkFastModListSync = checkFastModListSync
module.exports.saveFastModListSyncSnapshot = saveFastModListSyncSnapshot
module.exports.postInstallModpackFiles = postInstallModpackFiles
module.exports.detectModConflictsNative = detectModConflictsNative
module.exports.inspectPackMetadata = inspectPackMetadata
module.exports.scanPackDirectory = scanPackDirectory
module.exports.exportModpackArchive = exportModpackArchive
module.exports.LoaderType = LoaderType
module.exports.getInstancePath = getInstancePath
module.exports.createInstanceDirectories = createInstanceDirectories
module.exports.saveInstanceMeta = saveInstanceMeta
module.exports.loadInstanceMeta = loadInstanceMeta
module.exports.listInstances = listInstances
module.exports.deleteInstance = deleteInstance
module.exports.copyInstance = copyInstance
module.exports.getDirectorySize = getDirectorySize
module.exports.listInstanceMods = listInstanceMods
module.exports.toggleMod = toggleMod
module.exports.deleteMod = deleteMod
module.exports.listInstanceResourcepacks = listInstanceResourcepacks
module.exports.readLogTail = readLogTail
module.exports.extractZip = extractZip
module.exports.extractZipAsync = extractZipAsync
module.exports.extractFilesFromZip = extractFilesFromZip
module.exports.listZipContents = listZipContents
module.exports.readFileFromZip = readFileFromZip
module.exports.parseModrinthManifest = parseModrinthManifest
module.exports.parseCurseforgeManifest = parseCurseforgeManifest
module.exports.extractModpackOverrides = extractModpackOverrides
module.exports.modrinthSearch = modrinthSearch
module.exports.modrinthGetProject = modrinthGetProject
module.exports.modrinthGetVersions = modrinthGetVersions
module.exports.curseforgeSearch = curseforgeSearch
module.exports.curseforgeGetFiles = curseforgeGetFiles
module.exports.curseforgeGetDownloadUrl = curseforgeGetDownloadUrl
module.exports.fetchVersionManifest = fetchVersionManifest
module.exports.fetchVersionDetail = fetchVersionDetail
module.exports.prepareLaunch = prepareLaunch
module.exports.launchGame = launchGame
module.exports.getAssetDownloads = getAssetDownloads
module.exports.analyzeCrashLog = analyzeCrashLog
module.exports.ForgeLoaderType = ForgeLoaderType
module.exports.runForgeInstaller = runForgeInstaller
module.exports.installForge = installForge
module.exports.installFabric = installFabric
module.exports.getFabricVersions = getFabricVersions
module.exports.installQuilt = installQuilt
module.exports.getQuiltVersions = getQuiltVersions
module.exports.isProcessAlive = isProcessAlive
module.exports.killProcessTree = killProcessTree
module.exports.saveRunningInstance = saveRunningInstance
module.exports.removeRunningInstance = removeRunningInstance
module.exports.getRunningInstances = getRunningInstances
module.exports.isInstanceRunning = isInstanceRunning
module.exports.getInstancePid = getInstancePid
