/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync, readdirSync } = require('fs')
const { dirname, join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'process-tracker.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.android-arm64.node')
          } else {
            nativeBinding = require('process-tracker-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'process-tracker.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.android-arm-eabi.node')
          } else {
            nativeBinding = require('process-tracker-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'process-tracker.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.win32-x64-msvc.node')
          } else {
            nativeBinding = require('process-tracker-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'process-tracker.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('process-tracker-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'process-tracker.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('process-tracker-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'process-tracker.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./process-tracker.darwin-universal.node')
      } else {
        nativeBinding = require('process-tracker-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'process-tracker.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.darwin-x64.node')
          } else {
            nativeBinding = require('process-tracker-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'process-tracker.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.darwin-arm64.node')
          } else {
            nativeBinding = require('process-tracker-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'process-tracker.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./process-tracker.freebsd-x64.node')
      } else {
        nativeBinding = require('process-tracker-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-x64-musl.node')
            } else {
              nativeBinding = require('process-tracker-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-x64-gnu.node')
            } else {
              nativeBinding = require('process-tracker-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-arm64-musl.node')
            } else {
              nativeBinding = require('process-tracker-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('process-tracker-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('process-tracker-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('process-tracker-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('process-tracker-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'process-tracker.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./process-tracker.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('process-tracker-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'process-tracker.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./process-tracker.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('process-tracker-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { detectJavaInstallations, validateJavaPath, getRecommendedJavaVersion, findJavaForMinecraft, downloadFile, downloadFiles, verifyFileHash, calculateSha1, calculateSha256, verifyMultipleFileHashes, planServerSyncDownloads, cleanupExtraMods, checkFastModListSync, saveFastModListSyncSnapshot, postInstallModpackFiles, detectModConflictsNative, inspectPackMetadata, LoaderType, getInstancePath, createInstanceDirectories, saveInstanceMeta, loadInstanceMeta, listInstances, deleteInstance, copyInstance, getDirectorySize, listInstanceMods, toggleMod, deleteMod, listInstanceResourcepacks, readLogTail, extractZip, extractFilesFromZip, listZipContents, readFileFromZip, parseModrinthManifest, parseCurseforgeManifest, extractModpackOverrides, modrinthSearch, modrinthGetProject, modrinthGetVersions, curseforgeSearch, curseforgeGetFiles, curseforgeGetDownloadUrl, fetchVersionManifest, fetchVersionDetail, prepareLaunch, launchGame, getAssetDownloads, analyzeCrashLog, ForgeLoaderType, installForge, installFabric, getFabricVersions, installQuilt, getQuiltVersions, isProcessAlive, killProcessTree, saveRunningInstance, removeRunningInstance, getRunningInstances, isInstanceRunning, getInstancePid } = nativeBinding

module.exports.detectJavaInstallations = detectJavaInstallations
module.exports.validateJavaPath = validateJavaPath
module.exports.getRecommendedJavaVersion = getRecommendedJavaVersion
module.exports.findJavaForMinecraft = findJavaForMinecraft
module.exports.downloadFile = downloadFile
module.exports.downloadFiles = downloadFiles
module.exports.verifyFileHash = verifyFileHash
module.exports.calculateSha1 = calculateSha1
module.exports.calculateSha256 = calculateSha256
module.exports.verifyMultipleFileHashes = verifyMultipleFileHashes
module.exports.planServerSyncDownloads = planServerSyncDownloads
module.exports.cleanupExtraMods = cleanupExtraMods
module.exports.checkFastModListSync = checkFastModListSync
module.exports.saveFastModListSyncSnapshot = saveFastModListSyncSnapshot
module.exports.postInstallModpackFiles = postInstallModpackFiles
module.exports.detectModConflictsNative = detectModConflictsNative
module.exports.inspectPackMetadata = inspectPackMetadata
module.exports.LoaderType = LoaderType
module.exports.getInstancePath = getInstancePath
module.exports.createInstanceDirectories = createInstanceDirectories
module.exports.saveInstanceMeta = saveInstanceMeta
module.exports.loadInstanceMeta = loadInstanceMeta
module.exports.listInstances = listInstances
module.exports.deleteInstance = deleteInstance
module.exports.copyInstance = copyInstance
module.exports.getDirectorySize = getDirectorySize
module.exports.listInstanceMods = listInstanceMods
module.exports.toggleMod = toggleMod
module.exports.deleteMod = deleteMod
module.exports.listInstanceResourcepacks = listInstanceResourcepacks
module.exports.readLogTail = readLogTail
module.exports.extractZip = extractZip
module.exports.extractFilesFromZip = extractFilesFromZip
module.exports.listZipContents = listZipContents
module.exports.readFileFromZip = readFileFromZip
module.exports.parseModrinthManifest = parseModrinthManifest
module.exports.parseCurseforgeManifest = parseCurseforgeManifest
module.exports.extractModpackOverrides = extractModpackOverrides
module.exports.modrinthSearch = modrinthSearch
module.exports.modrinthGetProject = modrinthGetProject
module.exports.modrinthGetVersions = modrinthGetVersions
module.exports.curseforgeSearch = curseforgeSearch
module.exports.curseforgeGetFiles = curseforgeGetFiles
module.exports.curseforgeGetDownloadUrl = curseforgeGetDownloadUrl
module.exports.fetchVersionManifest = fetchVersionManifest
module.exports.fetchVersionDetail = fetchVersionDetail
module.exports.prepareLaunch = prepareLaunch
module.exports.launchGame = launchGame
module.exports.getAssetDownloads = getAssetDownloads
module.exports.analyzeCrashLog = analyzeCrashLog
module.exports.ForgeLoaderType = ForgeLoaderType
module.exports.installForge = installForge
module.exports.installFabric = installFabric
module.exports.getFabricVersions = getFabricVersions
module.exports.installQuilt = installQuilt
module.exports.getQuiltVersions = getQuiltVersions
module.exports.isProcessAlive = isProcessAlive
module.exports.killProcessTree = killProcessTree
module.exports.saveRunningInstance = saveRunningInstance
module.exports.removeRunningInstance = removeRunningInstance
module.exports.getRunningInstances = getRunningInstances
module.exports.isInstanceRunning = isInstanceRunning
module.exports.getInstancePid = getInstancePid

function parseJavaVersionOutput(output, javaPath) {
  const versionMatch = output.match(/(?:java|openjdk)\s+version\s+"([^"]+)"/i)
  if (!versionMatch || !versionMatch[1]) {
    return null
  }

  const version = versionMatch[1]
  const majorMatch = version.startsWith('1.')
    ? version.match(/^1\.(\d+)/)
    : version.match(/^(\d+)/)
  const majorVersion = majorMatch && majorMatch[1] ? Number.parseInt(majorMatch[1], 10) : 0

  let vendor = 'Unknown'
  if (output.includes('Temurin') || output.includes('Adoptium') || output.includes('AdoptOpenJDK')) {
    vendor = 'Adoptium'
  } else if (output.includes('Azul') || output.includes('Zulu')) {
    vendor = 'Azul Zulu'
  } else if (output.includes('Microsoft')) {
    vendor = 'Microsoft'
  } else if (output.includes('Oracle')) {
    vendor = 'Oracle'
  } else if (output.includes('OpenJDK')) {
    vendor = 'OpenJDK'
  }

  return {
    path: javaPath,
    version,
    majorVersion,
    vendor,
    is64Bit: /64-Bit|amd64|x86_64/i.test(output),
    isJdk: existsSync(join(dirname(javaPath), 'javac.exe')),
  }
}

function resolveJavaExecutable(javaPath) {
  if (!javaPath || !existsSync(javaPath)) {
    return null
  }

  try {
    const stats = require('fs').statSync(javaPath)
    if (stats.isDirectory()) {
      const directCandidate = join(javaPath, 'java.exe')
      if (existsSync(directCandidate)) {
        return directCandidate
      }

      const binCandidate = join(javaPath, 'bin', 'java.exe')
      if (existsSync(binCandidate)) {
        return binCandidate
      }

      return null
    }
  } catch {
    return null
  }

  return javaPath
}

function validateJavaPathSafe(javaPath) {
  const resolvedPath = resolveJavaExecutable(javaPath)
  if (!resolvedPath) {
    return null
  }

  try {
    const { spawnSync } = require('child_process')
    const result = spawnSync(resolvedPath, ['-version'], {
      encoding: 'utf8',
      timeout: 5000,
      windowsHide: true,
    })
    if (result.error || (result.status !== 0 && result.status !== null)) {
      return null
    }

    const output = `${result.stderr || ''}${result.stdout || ''}`.trim()
    return parseJavaVersionOutput(output, resolvedPath)
  } catch {
    return null
  }
}

function detectJavaInstallationsSafe() {
  const installations = []
  const seen = new Set()

  const addCandidate = (candidate) => {
    if (!candidate || seen.has(candidate) || !existsSync(candidate)) {
      return
    }
    seen.add(candidate)
    const info = validateJavaPathSafe(candidate)
    if (info) {
      installations.push(info)
    }
  }

  const scanBaseDir = (baseDir) => {
    if (!baseDir || !existsSync(baseDir)) {
      return
    }

    addCandidate(join(baseDir, 'java.exe'))
    addCandidate(join(baseDir, 'bin', 'java.exe'))

    try {
      const entries = readdirSync(baseDir, { withFileTypes: true })
      for (const entry of entries) {
        if (!entry.isDirectory()) {
          continue
        }
        addCandidate(join(baseDir, entry.name, 'bin', 'java.exe'))
      }
    } catch {}
  }

  const pathEntries = (process.env.PATH || '').split(';').filter(Boolean)
  for (const entry of pathEntries) {
    addCandidate(join(entry, 'java.exe'))
  }

  addCandidate(process.env.JAVA_HOME ? join(process.env.JAVA_HOME, 'bin', 'java.exe') : null)
  addCandidate(process.env.JRE_HOME ? join(process.env.JRE_HOME, 'bin', 'java.exe') : null)

  ;[
    'C:\\Program Files\\Common Files\\Oracle\\Java\\javapath',
    'C:\\Program Files\\Java',
    'C:\\Program Files (x86)\\Java',
    'C:\\Program Files\\Eclipse Adoptium',
    'C:\\Program Files\\Zulu',
    'C:\\Program Files\\Microsoft',
    'C:\\Program Files\\Microsoft\\jdk',
    'C:\\Program Files\\Amazon Corretto',
  ].forEach(scanBaseDir)

  installations.sort((a, b) => b.majorVersion - a.majorVersion)

  const recommended =
    installations.find((item) => item.is64Bit && (item.majorVersion === 21 || item.majorVersion === 17)) ||
    installations.find((item) => item.is64Bit && item.majorVersion >= 17) ||
    installations.find((item) => item.is64Bit) ||
    installations[0] ||
    null

  return {
    installations,
    recommended,
  }
}

function findJavaForMinecraftSafe(minecraftVersion) {
  const requiredVersion =
    typeof module.exports.getRecommendedJavaVersion === 'function'
      ? module.exports.getRecommendedJavaVersion(minecraftVersion)
      : 17
  const detection = detectJavaInstallationsSafe()
  return (
    detection.installations.find(
      (item) => item.is64Bit && item.majorVersion === requiredVersion,
    ) ||
    detection.installations.find(
      (item) => item.is64Bit && item.majorVersion >= requiredVersion,
    ) ||
    null
  )
}

if (platform === 'win32') {
  module.exports.detectJavaInstallations = detectJavaInstallationsSafe
  module.exports.validateJavaPath = validateJavaPathSafe
  module.exports.findJavaForMinecraft = findJavaForMinecraftSafe
}
