/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Represents a detected Java installation */
export interface JavaInstallation {
  path: string
  version: string
  majorVersion: number
  vendor: string
  is64Bit: boolean
  isJdk: boolean
}
/** Java detection result */
export interface JavaDetectionResult {
  installations: Array<JavaInstallation>
  recommended?: JavaInstallation
}
/** Detect all Java installations on the system */
export declare function detectJavaInstallations(): JavaDetectionResult
/** Validate a Java path */
export declare function validateJavaPath(path: string): JavaInstallation | null
/** Get recommended Java version for a Minecraft version */
export declare function getRecommendedJavaVersion(minecraftVersion: string): number
/** Find best Java for a Minecraft version from detected installations */
export declare function findJavaForMinecraft(minecraftVersion: string): JavaInstallation | null
export declare function installJavaRuntime(majorVersion: number, installRoot: string): Promise<string>
export interface DownloadTask {
  url: string
  path: string
  sha1?: string | null | undefined
  sha256?: string | null | undefined
  size?: number | null | undefined
}
export interface DownloadResult {
  success: boolean
  completed: number
  failed: number
  errors: Array<string>
}
export interface SingleDownloadResult {
  success: boolean
  path: string
  error?: string
}
export declare function downloadFile(url: string, path: string, sha1?: string | undefined | null, sha256?: string | undefined | null): Promise<SingleDownloadResult>
export declare function downloadFiles(tasks: Array<DownloadTask>, maxConcurrent?: number | undefined | null): Promise<DownloadResult>
export declare function verifyFileHash(path: string, sha1?: string | undefined | null, sha256?: string | undefined | null): Promise<boolean>
export declare function calculateSha1(path: string): Promise<string | null>
export declare function calculateSha256(path: string): Promise<string | null>
export interface HashCheckTask {
  filePath: string
  expectedSha1?: string | null | undefined
  expectedSha256?: string | null | undefined
  expectedSha512?: string | null | undefined
}
export interface HashCheckResult {
  filePath: string
  isValid: boolean
}
export declare function verifyMultipleFileHashes(tasks: Array<HashCheckTask>): Promise<Array<HashCheckResult>>
export interface ServerModEntry {
  filename: string
  url: string
  size?: number | null | undefined
  hash?: string | null | undefined
}
export interface ServerSyncPlanResult {
  downloadQueue: Array<ServerModEntry>
  inspected: number
  queued: number
  skippedUnsafe: number
}
export interface CleanupExtraModsResult {
  scanned: number
  deleted: number
  keptLocked: number
}
export interface FastModListSyncSnapshot {
  manifestRevision: string
  serverModsSignature: string
  lockedModsSignature: string
  localModsSignature: string
}
export interface FastModListSyncCheckResult {
  canSkip: boolean
  snapshot: FastModListSyncSnapshot
}
export interface PostInstallModpackFilesResult {
  movedResourcepacks: number
  removedDuplicates: number
}
export interface NativeModConflict {
  conflictType: string
  file1: string
  file2?: string | null | undefined
  reason: string
}
export interface PackMetadataResult {
  iconBase64?: string | null | undefined
  version?: string | null | undefined
  packFormat?: number | null | undefined
}
export declare function planServerSyncDownloads(gameDir: string, mods: Array<ServerModEntry>): Promise<ServerSyncPlanResult>
export declare function cleanupExtraMods(gameDir: string, serverFilenames: Array<string>, lockedMods?: Array<string> | undefined | null): Promise<CleanupExtraModsResult>
export declare function checkFastModListSync(gameDir: string, manifestRevision: string, serverFilenames: Array<string>, lockedMods?: Array<string> | undefined | null): Promise<FastModListSyncCheckResult>
export declare function saveFastModListSyncSnapshot(gameDir: string, snapshot: FastModListSyncSnapshot): Promise<boolean>
export declare function postInstallModpackFiles(gameDir: string): Promise<PostInstallModpackFilesResult>
export declare function detectModConflictsNative(modsDir: string): Array<NativeModConflict>
export declare function inspectPackMetadata(packPath: string, packKind: string): Promise<PackMetadataResult>
export interface PackScanEntry {
  filename: string
  displayName: string
  isDirectory: boolean
  size: number
  modifiedAt: string
  enabled: boolean
  iconBase64?: string | null | undefined
  version?: string | null | undefined
  packFormat?: number | null | undefined
}
export declare function scanPackDirectory(directory: string, packKind: string): Promise<Array<PackScanEntry>>
export interface ModpackExportRequest {
  instanceDir: string
  outputPath: string
  format: string
  includedPaths: Array<string>
  name: string
  version: string
  description?: string | null | undefined
  minecraftVersion: string
  loader: string
  loaderVersion?: string | null | undefined
}
export interface ModpackExportResult {
  success: boolean
  filesWritten: number
  totalBytes: number
}
export declare function exportModpackArchive(request: ModpackExportRequest): Promise<ModpackExportResult>
/** Instance loader type */
export const enum LoaderType {
  Vanilla = 'Vanilla',
  Fabric = 'Fabric',
  Forge = 'Forge',
  NeoForge = 'NeoForge',
  Quilt = 'Quilt'
}
/** Game instance metadata */
export interface InstanceMeta {
  id: string
  name: string
  icon?: string
  banner?: string
  minecraftVersion: string
  loader: string
  loaderVersion?: string
  createdAt: string
  lastPlayedAt?: string
  totalPlayTime: number
  javaPath?: string
  ramMb?: number
  javaArguments?: string
  gameDirectory: string
  modpackId?: string
  modpackVersionId?: string
  cloudId?: string
  autoUpdate?: boolean
  lockedMods?: Array<string>
}
/** Mod info */
export interface ModInfo {
  filename: string
  name?: string
  version?: string
  description?: string
  authors?: Array<string>
  modId?: string
  iconBase64?: string | null | undefined
  enabled: boolean
  size: number
}
/** Resource pack info */
export interface ResourcePackInfo {
  filename: string
  name?: string
  description?: string
  packFormat?: number
  size: number
}
/** Directory size info */
export interface DirectorySizeInfo {
  totalBytes: number
  fileCount: number
  folderCount: number
}
/** Get instance directory path */
export declare function getInstancePath(baseDir: string, instanceId: string): string
/** Create instance directory structure */
export declare function createInstanceDirectories(baseDir: string, instanceId: string): boolean
/** Save instance metadata */
export declare function saveInstanceMeta(baseDir: string, instanceId: string, meta: InstanceMeta): boolean
/** Load instance metadata */
export declare function loadInstanceMeta(baseDir: string, instanceId: string): InstanceMeta | null
/** List all instances with optional pagination */
export declare function listInstances(baseDir: string, offset?: number | undefined | null, limit?: number | undefined | null): Promise<Array<InstanceMeta>>
/** Delete instance directory */
export declare function deleteInstance(baseDir: string, instanceId: string): Promise<boolean>
/** Copy instance */
export declare function copyInstance(baseDir: string, sourceId: string, destId: string, newName: string): Promise<boolean>
/** Get directory size */
export declare function getDirectorySize(path: string): DirectorySizeInfo
/** List mods in instance */
export declare function listInstanceMods(baseDir: string, instanceId: string): Array<ModInfo>
/** Toggle mod enabled/disabled */
export declare function toggleMod(baseDir: string, instanceId: string, filename: string, enabled: boolean): boolean
/** Delete mod from instance */
export declare function deleteMod(baseDir: string, instanceId: string, filename: string): boolean
/** List resource packs in instance */
export declare function listInstanceResourcepacks(baseDir: string, instanceId: string): Array<ResourcePackInfo>
export declare function readLogTail(filePath: string, maxLines?: number | undefined | null, maxBytes?: number | undefined | null): string
/** Extraction progress */
export interface ExtractProgress {
  current: number
  total: number
  currentFile: string
  bytesExtracted: number
}
/** Extraction result */
export interface ExtractResult {
  success: boolean
  filesExtracted: number
  error?: string
}
/** Extract a ZIP file to a directory */
export declare function extractZip(zipPath: string, destPath: string, stripPrefix?: string | undefined | null): ExtractResult
export declare function extractZipAsync(zipPath: string, destPath: string, stripPrefix?: string | undefined | null): Promise<ExtractResult>
/** Extract specific files from a ZIP */
export declare function extractFilesFromZip(zipPath: string, destPath: string, files: Array<string>): ExtractResult
/** List files in a ZIP archive */
export declare function listZipContents(zipPath: string): Array<string>
/** Read a file from inside a ZIP without extracting */
export declare function readFileFromZip(zipPath: string, filePath: string): string | null
/** Modrinth modpack manifest */
export interface ModrinthManifest {
  formatVersion: number
  game: string
  versionId: string
  name: string
  summary?: string
  files: Array<ModrinthManifestFile>
  minecraftVersion?: string
  loader?: string
  loaderVersion?: string
}
export interface ModrinthManifestFile {
  path: string
  hashes: ModrinthFileHashes
  downloads: Array<string>
  fileSize: number
  env?: ModrinthFileEnv
}
export interface ModrinthFileHashes {
  sha1: string
  sha512?: string
}
export interface ModrinthFileEnv {
  client?: string
  server?: string
}
/** Parse Modrinth modpack manifest from .mrpack file */
export declare function parseModrinthManifest(mrpackPath: string): ModrinthManifest | null
/** CurseForge modpack manifest */
export interface CurseForgeManifest {
  minecraft: CurseForgeMinecraft
  manifestType: string
  manifestVersion: number
  name: string
  version: string
  author: string
  files: Array<CurseForgeManifestFile>
  overrides: string
}
export interface CurseForgeMinecraft {
  version: string
  modLoaders: Array<CurseForgeModLoader>
}
export interface CurseForgeModLoader {
  id: string
  primary: boolean
}
export interface CurseForgeManifestFile {
  projectId: number
  fileId: number
  required: boolean
}
/** Parse CurseForge modpack manifest */
export declare function parseCurseforgeManifest(zipPath: string): CurseForgeManifest | null
/** Extract modpack overrides to instance directory */
export declare function extractModpackOverrides(zipPath: string, instancePath: string, overridesFolder?: string | undefined | null): ExtractResult
export interface ModrinthSearchOptions {
  query?: string
  projectType?: string
  gameVersion?: string
  loader?: string
  limit?: number
  offset?: number
  sortBy?: string
}
export interface ModrinthProject {
  projectId: string
  projectType: string
  slug?: string
  title: string
  description: string
  categories?: Array<string>
  displayCategories?: Array<string>
  clientSide: string
  serverSide: string
  downloads: number
  follows: number
  iconUrl?: string
  author: string
  versions?: Array<string>
  gameVersions?: Array<string>
  loaders?: Array<string>
  license?: string
  color?: number
  latestVersion?: string
  dateCreated: string
  dateModified: string
  gallery?: Array<ModrinthGalleryItem>
  featuredGallery?: string
}
export interface ModrinthSearchProject {
  projectId: string
  projectType: string
  slug?: string
  title: string
  description: string
  categories?: Array<string>
  displayCategories?: Array<string>
  clientSide: string
  serverSide: string
  downloads: number
  follows: number
  iconUrl?: string
  author: string
  versions?: Array<string>
  gameVersions?: Array<string>
  loaders?: Array<string>
  license?: string
  color?: number
  latestVersion?: string
  dateCreated: string
  dateModified: string
  gallery?: Array<string>
  featuredGallery?: string
}
export interface ModrinthSearchResult {
  hits: Array<ModrinthSearchProject>
  offset: number
  limit: number
  totalHits: number
}
export interface ModrinthFile {
  url: string
  filename: string
  primary?: boolean
}
export interface ModrinthVersion {
  id: string
  projectId: string
  authorId?: string
  name: string
  versionNumber: string
  gameVersions: Array<string>
  loaders: Array<string>
  versionType: string
  status?: string
  featured?: boolean
  changelog?: string
  files: Array<ModrinthFile>
  datePublished: string
  downloads: number
}
export interface ModrinthGalleryItem {
  url: string
  rawUrl?: string
  featured: boolean
  title?: string
  description?: string
  created: string
  ordering: number
}
export declare function modrinthSearch(options: ModrinthSearchOptions): Promise<ModrinthSearchResult>
export declare function modrinthGetProject(projectId: string): Promise<ModrinthProject>
export declare function modrinthGetVersions(projectId: string): Promise<Array<ModrinthVersion>>
export interface CurseForgeLogo {
  id: number
  url: string
  title: string
  thumbnailUrl: string
}
export interface CurseForgeCategory {
  id: number
  gameId: number
  name: string
  slug: string
  url: string
  iconUrl: string
  dateModified: string
  isClass?: boolean
  classId?: number
  parentCategoryId?: number
}
export interface CurseForgeAuthor {
  name: string
  url: string
  id: number
}
export interface CurseForgeFile {
  id: number
  displayName: string
  fileName: string
  fileDate: string
  fileLength?: number
  releaseType: number
  fileStatus: number
  downloadUrl?: string
  isAvailable: boolean
  gameVersions?: Array<string>
  sortableGameVersions?: Array<CurseForgeSortableGameVersion>
}
export interface CurseForgeSortableGameVersion {
  gameVersionName?: string
  gameVersionPadded?: string
  gameVersion?: string
  gameVersionReleaseDate?: string
  gameVersionTypeId?: number
}
export interface CurseForgeFileIndex {
  gameVersion: string
  fileId: number
  filename: string
  releaseType: number
}
export interface CurseForgeLinks {
  websiteUrl: string
  wikiUrl?: string
  issuesUrl?: string
  sourceUrl?: string
}
export interface CurseForgeScreenshot {
  id: number
  title?: string
  description?: string
  url: string
  thumbnailUrl: string
}
export interface CurseForgeProject {
  id: number
  classId?: number
  name: string
  slug: string
  summary: string
  links?: CurseForgeLinks
  downloadCount: number
  thumbsUpCount: number
  logo?: CurseForgeLogo
  screenshots?: Array<CurseForgeScreenshot>
  authors: Array<CurseForgeAuthor>
  categories: Array<CurseForgeCategory>
  mainFileId: number
  latestFiles: Array<CurseForgeFile>
  latestFilesIndexes?: Array<CurseForgeFileIndex>
  dateCreated: string
  dateModified: string
  dateReleased?: string
}
export interface CurseForgePagination {
  index: number
  pageSize: number
  resultCount: number
  totalCount: number
}
export interface CurseForgeSearchResult {
  data: Array<CurseForgeProject>
  pagination: CurseForgePagination
}
export interface CurseForgeSearchOptions {
  query?: string
  projectType?: string
  gameVersion?: string
  sortBy?: string
  pageSize?: number
  index?: number
}
export declare function curseforgeSearch(options: CurseForgeSearchOptions): Promise<CurseForgeSearchResult>
export interface CurseForgeFilesResult {
  data: Array<CurseForgeFile>
}
export declare function curseforgeGetFiles(projectId: number): Promise<CurseForgeFilesResult>
/** Get download URL for a CurseForge file */
export declare function curseforgeGetDownloadUrl(projectId: number, fileId: number): Promise<string | null>
export interface VersionManifest {
  latest: LatestVersions
  versions: Array<VersionInfo>
}
export interface LatestVersions {
  release: string
  snapshot: string
}
export interface VersionInfo {
  id: string
  versionType: string
  url: string
  time: string
  releaseTime: string
  sha1?: string
}
export interface LaunchOptions {
  instanceId: string
  versionId: string
  javaPath: string
  gameDir: string
  assetsDir: string
  librariesDir: string
  nativesDir: string
  versionJarPath: string
  username: string
  uuid: string
  accessToken: string
  userType: string
  ramMinMb?: number
  ramMaxMb?: number
  extraJvmArgs?: Array<string>
  extraGameArgs?: Array<string>
  windowWidth?: number
  windowHeight?: number
  fullscreen?: boolean
  serverAddress?: string
  serverPort?: number
  assetIndex?: string
}
export interface LaunchResult {
  success: boolean
  pid?: number
  error?: string
}
export interface DownloadItem {
  url: string
  path: string
  sha1?: string
  size?: number
}
export interface PrepareResult {
  success: boolean
  downloadsNeeded: Array<DownloadItem>
  classpath: Array<string>
  mainClass: string
  gameArgs: Array<string>
  jvmArgs: Array<string>
  error?: string
}
/** Fetch the Minecraft version manifest */
export declare function fetchVersionManifest(): Promise<VersionManifest>
/** Fetch version detail JSON */
export declare function fetchVersionDetail(url: string): Promise<string>
/** Prepare game launch - returns what needs to be downloaded and launch args */
export declare function prepareLaunch(versionJson: string, options: LaunchOptions): Promise<PrepareResult>
/** Launch the game process */
export declare function launchGame(javaPath: string, jvmArgs: Array<string>, mainClass: string, gameArgs: Array<string>, gameDir: string): LaunchResult
/** Get asset index and return download items for missing assets */
export declare function getAssetDownloads(assetIndexUrl: string, assetsDir: string): Promise<Array<DownloadItem>>
export declare function analyzeCrashLog(stderr: string): string | null
export const enum ForgeLoaderType {
  Forge = 'Forge',
  NeoForge = 'NeoForge'
}
export interface ForgeVersionInfo {
  forgeVersion: string
  mcVersion: string
  loaderType: ForgeLoaderType
  installerUrl: string
  versionJsonPath: string
}
export interface ForgeInstallerRunResult {
  success: boolean
  timeout: boolean
  exitCode?: number
  error?: string
}
export declare function runForgeInstaller(javaPath: string, installerPath: string, minecraftDir: string, timeoutMs?: number | undefined | null): Promise<ForgeInstallerRunResult>
/** Install Forge/NeoForge */
export declare function installForge(mcVersion: string, loaderType: ForgeLoaderType, loaderVersion: string | undefined | null, gameDir: string, javaPath?: string | undefined | null): Promise<string>
export interface FabricInstallResult {
  versionId: string
  versionJsonPath: string
  mainClass: string
  librariesJson: string
}
/**
 * Install Fabric loader for a Minecraft version
 * Returns the path to the generated version JSON
 */
export declare function installFabric(mcVersion: string, requestedLoaderVersion: string | undefined | null, minecraftDir: string): Promise<FabricInstallResult>
/** Get available Fabric loader versions for a Minecraft version */
export declare function getFabricVersions(mcVersion: string): Promise<Array<string>>
export interface QuiltInstallResult {
  versionId: string
  versionJsonPath: string
  mainClass: string
  librariesJson: string
}
/**
 * Install Quilt loader for a Minecraft version
 * Returns the path to the generated version JSON
 */
export declare function installQuilt(mcVersion: string, requestedLoaderVersion: string | undefined | null, minecraftDir: string): Promise<QuiltInstallResult>
/** Get available Quilt loader versions for a Minecraft version */
export declare function getQuiltVersions(mcVersion: string): Promise<Array<string>>
export declare function isProcessAlive(pid: number): boolean
export declare function killProcessTree(pid: number): boolean
export declare function saveRunningInstance(instanceId: string, pid: number, gameDir: string): boolean
export declare function removeRunningInstance(instanceId: string): boolean
export declare function getRunningInstances(): Array<RunningInstanceJs>
export declare function isInstanceRunning(instanceId: string): boolean
export declare function getInstancePid(instanceId: string): number | null
export interface RunningInstanceJs {
  instanceId: string
  pid: number
  startTime: number
  gameDir: string
}
